spring:
  application:
    name: yrkesskade-json-to-pdf
  main:
    banner-mode: OFF
  sleuth:
    baggage:
      remote-fields:
        - Nav-Callid
        - Nav-Consumer-Id
      correlation-fields:
        - Nav-Callid
        - Nav-Consumer-Id
  mvc:
    throw-exception-if-no-handler-found: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  servlet:
    multipart:
      #  Size limitations are also handled by app itself to get nice fault messages, but this setting seems to fail faster?
      max-request-size: 8MB
      max-file-size: 8MB
  codec:
    max-in-memory-size: 16MB
  jackson:
    deserialization:
      fail-on-unknown-properties: false
maxAttachmentSize: 8MB

server:
  port: 7093
  error:
    whitelabel:
      enabled: false
  shutdown: graceful

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}


navCallId: Nav-Callid
navConsumerId: Nav-Consumer-Id

allowed.origins:
  https://kompys.intern.nav.no,
  https://kompys.dev.intern.nav.no

