apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: yrkesskade-json-to-pdf
  namespace: yrkesskade
  labels:
    team: yrkesskade
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  image: {{ image }}
  port: 7093
  startup:
    failureThreshold: 20
    initialDelay: 30
    path: /internal/health
    periodSeconds: 10
    timeout: 2
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 400m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |ingress|}}
    - {{ingress}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /internal/prometheus
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: yrkesskade-saksbehandling-backend
  azure:
    application:
      enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
  {{#each envs}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
